require("ape")

-- load packer plugin configuration
-- require("ape.plugins")
if vim.o.loadplugins then
  ape.plugin.load("Comment.nvim")
  ape.plugin.load("Comment.nvim")
  ape.plugin.load("LuaSnip")
  ape.plugin.load("Shade.nvim")
  ape.plugin.load("cmp-buffer")
  ape.plugin.load("cmp-cmdline")
  ape.plugin.load("cmp-emoji")
  ape.plugin.load("cmp-nvim-lsp")
  ape.plugin.load("cmp-nvim-lua")
  ape.plugin.load("cmp-path")
  ape.plugin.load("cmp-spell")
  ape.plugin.load("cmp_luasnip")
  ape.plugin.load("command-t")
  ape.plugin.load("copilot.vim")
  ape.plugin.load("corpus")
  ape.plugin.load("edgedb-vim")
  ape.plugin.load("gitsigns.nvim")
  ape.plugin.load("indent-blankline.nvim")
  ape.plugin.load("loupe")
  -- ape.plugin.load("neodev.nvim")
  ape.plugin.load("lualine.nvim")
  ape.plugin.load("markdown-preview.nvim")
  ape.plugin.load("material.nvim")
  ape.plugin.load("nvim-autopairs")
  ape.plugin.load("nvim-autopairs")
  ape.plugin.load("nvim-cmp")
  ape.plugin.load("nvim-jdtls")
  ape.plugin.load("nvim-lightbulb")
  ape.plugin.load("nvim-lspconfig")
  ape.plugin.load("nvim-metals")
  ape.plugin.load("nvim-tree.lua")
  ape.plugin.load("nvim-treesitter")
  ape.plugin.load("nvim-treesitter-textobjects")
  ape.plugin.load("nvim-ts-autotag")
  ape.plugin.load("nvim-ts-context-commentstring")
  ape.plugin.load("nvim-web-devicons")
  ape.plugin.load("plenary.nvim")
  ape.plugin.load("replay")
  ape.plugin.load("vim-dirvish")
  ape.plugin.load("vim-dirvish")
  ape.plugin.load("vim-eunuch")
  ape.plugin.load("vim-fugitive")
  ape.plugin.load("vim-repeat")
  ape.plugin.load("vim-rhubarb")
  ape.plugin.load("vim-speeddating")
  ape.plugin.load("vim-surround")
end

require("wincent.commandt").setup()

require("ape.lsp")
require("ape.metals")
