#!/bin/zsh

alias v="nvim"
alias j="jump"
alias vim="nvim"
alias g="git"
alias ls="ls -hF --color=auto"
alias l="ls -hF --color=auto"
alias ll="ls -lAhF --color=auto"
alias week="date +%V"
alias R="R --quiet"
alias e="exit"
alias f="find -name"
alias t="tmux"
# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'
