brew "bat"
brew "cloc"
brew "eza"
brew "ffmpeg"
brew "fish"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "jj"
brew "mas"
brew "pam-reattach"
brew "ripgrep"
brew "stow"
brew "svtplay-dl"
brew "tmux"
brew "tree"
brew "vim"

cask "1password"
cask "1password-cli"
cask "android-studio"
cask "arq"
cask "cleanshot"
cask "discord"
cask "figma"
cask "firefox"
cask "flox"
cask "get-api"
cask "ghostty"
cask "google-chrome"
cask "istat-menus"
cask "karabiner-elements"
cask "linear-linear"
cask "logi-options+"
cask "monodraw"
cask "obsidian"
cask "orbstack"
cask "parallels"
cask "raycast"
cask "slack"
cask "spotify"
cask "tableplus"
cask "tailscale-app"
cask "zed"

cask "font-jetbrains-mono"
cask "font-source-code-pro"

mas "1Password for Safari", id: 1569813296
mas "Hand Mirror", id: 1502839586
mas "Keynote", id: 409183694
mas "Minimal Theme for Twitter / X", id: 1668204600
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
