let mapleader="\<Space>"             " Change leader key to <Space>

let g:netrw_home="~/.cache/nvim/"    " Move annoying files out of the way

let g:python3_host_prog="~/.local/share/virtualenvs/neovim-virtualenv-OrBhBdWR/bin/python"
let g:loaded_python_provider=0	     " Disable python2

let g:deoplete#enable_at_startup = 1 " Use deoplete

if &loadplugins
  if has("packages")
    packadd! command-t
    packadd! kotlin-vim
    packadd! python-syntax
    packadd! tabular
    packadd! ultisnips
    packadd! vim-fugitive
    packadd! vim-jsx-pretty
    packadd! vim-snippets
    packadd! vim-surround

    if has("nvim")
      packadd! corpus
      packadd! deoplete.nvim
    endif
  endif
endif

if has('nvim')
  lua <<
    CorpusDirectories = {
      ['~/Documents/notes'] = {
        autocommit = true,
        autoreference = 1,
        autotitle = 1,
        base = './',
        transform = 'local',
      }
  }
.
endif

filetype indent plugin on	     " Enable ft detection, indentation and load plugin file 
syntax on			     " Enable syntax highlighting
