let mapleader="\<Space>"          " Change leader key to <Space>

let g:netrw_home="~/.cache/nvim/" " Move annoying files out of the way

if &loadplugins
  if has("packages")
    packadd! command-t
    packadd! corpus
    packadd! tabular
  endif
endif

if has('nvim')
  lua <<
    CorpusDirectories = {
      ['~/Documents/notes'] = {
        autocommit = true,
        autoreference = 1,
        autotitle = 1,
        base = './',
        transform = 'local',
      }
  }
.
endif


filetype indent plugin on	  " Enable ft detection, indentation and load plugin file 
syntax on			  " Enable syntax highlighting
