#!/bin/zsh

alias v="nvim"
alias j="jump"
alias g="git"
alias ls="ls -hF --color=auto"
alias l="ls -hF --color=auto"
alias ll="ls -lAhF --color=auto"
alias week="date +%V"
alias R="R --quiet"
alias e="exit"
alias f="find -name"
alias t="tmux"
alias path="echo -e ${PATH//:/\n}" # Pretty print path
alias tree="tree -I node_modules"
alias ssh="kitty +kitten ssh"
alias update="brew update && brew upgrade && mas upgrade"
alias scala="cs launch scala3-compiler:3+ -M dotty.tools.MainGenericRunner -- "
alias scalac="cs launch scala3-compiler:3+ -- "
alias cat="bat"
