#!/bin/zsh

alias cat="bat"
alias e="exit"
alias g="git"
alias h="history"
alias j="jump"
alias l="ls -hF --color=auto"
alias ll="ls -lAhF --color=auto"
alias ls="ls -hF --color=auto"
alias python="python3"
alias t="tmux"
alias tree="tree -I node_modules"
alias ts="tmux_session"
alias update="brew update && brew upgrade && mas upgrade"
alias v="nvim"
alias vim="nvim"
alias week="date +%V"
