# Taps
tap "homebrew/bundle"

# Formula
brew "fish"                # User-friendly command-line shell for UNIX-like operating systems
brew "mas"                 # Mac App Store command-line interface
brew "pinentry-mac"        # Pinentry for GPG on Mac

# Casks
cask "ghostty"             # Terminal emulator that uses platform-native UI and GPU acceleration
cask "1password"           # Password manager that keeps all passwords secure behind one password
cask "arc"                 # Chromium based browser
cask "arq"                 # Multi-cloud backup application
cask "cleanshot"           # Screen capturing tool
cask "discord"             # Voice and text chat software
cask "dropbox"             # Client for the Dropbox cloud storage service
cask "figma"               # Collaborative team software
cask "flox"                # Manages environments across the software lifecycle
cask "hey"                 # Access the HEY email service
cask "jordanbaird-ice"     # Menu bar manager
cask "karabiner-elements"  # Keyboard customiser
cask "linear-linear"       # App to manage software development and track bugs
cask "logi-options+"       # Software for Logitech devices
cask "monodraw"            # Tool to create text-based art
cask "obsidian"            # Knowledge base that works on top of a local folder of plain text Markdown files
cask "orbstack"            # Replacement for Docker Desktop
cask "raycast"             # Control your tools with a few keystrokes
cask "slack"               # Team communication and collaboration software
cask "spotify"             # Music streaming service
cask "tableplus"           # Native GUI tool for relational databases
cask "zed"                 # Multiplayer code editor

# Fonts
cask "font-jetbrains-mono"
cask "font-geist"
cask "font-geist-mono"

# App Store
mas "Hand Mirror", id: 1502839586
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
