tap "coursier/formulas"
tap "grishka/grishka"
tap "homebrew/bundle"
tap "homebrew/services"
# Mac App Store command-line interface
brew "mas"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Chromium based browser
cask "arc"
# Multi-cloud backup application
cask "arq"
# Screen capturing tool
cask "cleanshot"
# Voice and text chat software
cask "discord"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Collaborative team software
cask "figma"
# Manages environments across the software lifecycle
cask "flox"
cask "font-source-code-pro"
# Access the HEY email service
cask "hey"
# Menu bar manager
cask "jordanbaird-ice"
# Keyboard customiser
cask "karabiner-elements"
# GPU-based terminal emulator
cask "kitty"
# Software for Logitech devices
cask "logi-options+"
# Tool to create text-based art
cask "monodraw"
# Unofficial Google Nearby Share app
cask "neardrop"
# App to write, plan, collaborate, and get organised
cask "notion"
# Calendar for professionals and teams
cask "notion-calendar"
# Replacement for Docker Desktop
cask "orbstack"
# Control your tools with a few keystrokes
cask "raycast"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Native GUI tool for relational databases
cask "tableplus"
# Multiplayer code editor
cask "zed"
# Video communication and virtual meeting platform
cask "zoom"
mas "Hand Mirror", id: 1502839586
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
