#!/usr/bin/env bash

set -e

source "$(dirname "$0")/common"

log_info "Checking if Homebrew is installed"

if [ -x /opt/homebrew/bin/brew ]; then
  log_info "Homebrew is already installed."
else
  log_info "Installing Homebrew..."

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  log_info "Homebrew installation completed."
fi

export PATH="/opt/homebrew/bin:$PATH"

log_info "Installing packages using Homebrew"
brew bundle --zap

log_info "Symlinking dotfiles"
stow --target=$HOME files

log_info "Changing default shell to fish"
sudo chsh -s $(which fish) $(whoami)

log_info "Updating Git remote URLs from HTTPS to SSH"
git_remote_url=$(git config --get remote.origin.url)

if [[ "$git_remote_url" =~ ^https://github ]]; then
    ssh_url=$(echo "$git_remote_url" | sed 's|https://github.com/|git@github.com:|')
    git remote set-url origin "$ssh_url"
    log_info "Updated remote URL to SSH format"
else
    log_info "Remote URL already using SSH format"
fi
