#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# Source common functions
source "$(dirname "$0")/common"

# Dock
defaults write com.apple.dock autohide-delay -int 0
defaults write com.apple.dock autohide-time-modifier -float 0.4

killall Dock

# Keyboard repeat
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1
defaults write -g ApplePressAndHoldEnabled -bool false
