alias cat="bat"
alias e="exit"
alias d="hash -d"
alias g="git"
alias h="history"
alias j="jump"
alias l="gls -hF --color=auto"
alias ll="gls -lAhF --color=auto"
alias ls="gls -hF --color=auto"
alias week="date +%V"
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
