let mapleader="\<Space>" " Change leader key

" Define neovim-ruby-host path
let g:ruby_host_prog = "$HOME/.gem/ruby/2.7.0/bin/neovim-ruby-host"

let g:deoplete#enable_at_startup = 1
" Cycle through completions with <tab> and <S-tab>
inoremap <silent><expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <silent><expr><s-tab> pumvisible() ? "\<c-p>" : "\<S-tab>"

" Close documentation window when completion is done
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>

let g:LanguageClient_useFloatingHover=1
let g:LanguageClient_hoverPreview='Always'
let g:LanguageClient_serverCommands = {
    \ 'python': ['~/.local/bin/pyls'],
    \ 'sh': ['bash-language-server', 'start'],
    \ 'latex': ['texlab']
    \ }

" Load plugins
if &loadplugins
  if has("packages")
    packadd! base16-vim
    packadd! command-t
    packadd! deoplete.nvim
    packadd! LanguageClient-neovim
    packadd! tabular
    packadd! ultisnips
    packadd! vim-surround
  endif
endif

let base16colorspace=256 " Enable 256 bit colors
set background=dark
colorscheme base16-seti  " Set the colorscheme

" Enable transparent background
hi Normal ctermbg=none
hi NonText ctermbg=none

" Remove underline
hi CursorLineNr cterm=none 

" Enable italic comments
hi Comment cterm=italic

" Change highlighting of spell errors 
hi clear SpellCap
hi SpellCap cterm=underline ctermfg=yellow
hi SpellBad cterm=underline 
