let mapleader="\<Space>" " Change leader key

" Highlight yanked text
au TextYankPost * silent! lua require'vim.highlight'.on_yank("IncSearch", 300)

" Define neovim-ruby-host path
let g:ruby_host_prog="$HOME/.gem/ruby/2.7.0/bin/neovim-ruby-host"
let g:python3_host_prog="/usr/bin/python"
let g:loaded_python_provider=0  " Disable python2 support

nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>

let g:LanguageClient_useFloatingHover=1
let g:LanguageClient_hoverPreview='Always'
let g:LanguageClient_serverCommands = {
    \ 'python': ['~/.local/bin/pyls'],
    \ 'kotlin': ['~/.local/share/kotlin-language-server/server/build/install/server/bin/kotlin-language-server']
    \ }

" Load plugins
if &loadplugins
  if has("packages")
    packadd! base16-vim
    packadd! command-t
    packadd! deoplete.nvim
    packadd! follow-markdown-links
    packadd! kotlin-vim
    packadd! LanguageClient-neovim
    packadd! python-syntax
    packadd! tabular
    packadd! ultisnips
    packadd! vim-markdown
    packadd! vim-surround
  endif
endif

" Move annoying files out of the way
let g:netrw_home="~/.cache/nvim/"

if filereadable(expand("~/.cache/base16-shell/.vimrc_background"))
  let base16colorspace=256
  source ~/.cache/base16-shell/.vimrc_background
endif

filetype indent plugin on
syntax on
