# Flox manifest version managed by Flox CLI
version = 1

[install]
_1password.pkg-path = "_1password"
bat.pkg-path = "bat"
cloc.pkg-path = "cloc"
coreutils-full.pkg-path = "coreutils-full"
curl.pkg-path = "curl"
delta.pkg-path = "delta"
eza.pkg-path = "eza"
ffmpeg.pkg-path = "ffmpeg"
findutils.pkg-path = "findutils"
git-lfs.pkg-path = "git-lfs"
gitFull.pkg-path = "gitFull"
github-cli.pkg-path = "github-cli"
glow.pkg-path = "glow"
gnumake.pkg-path = "gnumake"
gnupg.pkg-path = "gnupg"
gnused.pkg-path = "gnused"
gnutar.pkg-path = "gnutar"
imagemagick.pkg-path = "imagemagick"
jq.pkg-path = "jq"
man.pkg-path = "man"
openssh.pkg-path = "openssh"
ripgrep.pkg-path = "ripgrep"
svtplay-dl.pkg-path = "svtplay-dl"
tmux.pkg-path = "tmux"
tree.pkg-path = "tree"

[vars]

[hook]

[profile]

[services]

[options]
systems = ["aarch64-darwin", "x86_64-darwin", "aarch64-linux", "x86_64-linux"]

# Uncomment to disable CUDA detection.
# cuda-detection = false
